version: "3"
services:

  clickhouse:
    image: docker.io/clickhouse/clickhouse-server:23
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    ports:
      - "9000:9000"
      - "8123:8123"

